create table if not exists public.companies (
  id uuid not null default gen_random_uuid(),
  name text null default ''::text,
  website_url text null,
  linkedin_url text null,
  twitter_url text null,
  facebook_url text null,
  logo_url text null,
  primary_domain text null,
  industry text null,
  keywords jsonb null,
  phone text null,
  country text null,
  estimated_num_employees bigint null,
  created_at timestamp with time zone null default now(),
  comments jsonb[] null,
  world_area text null,
  constraint companies_pkey primary key (id)
);

create table if not exists public.show_participation (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  company_id text null,
  show_id text null,
  year text null,
  booth_number text null,
  booth_size text null,
  booth_size_category text null,
  constraint show_participation_pkey primary key (id)
);

create index if not exists idx_show_participation_show_id
  on public.show_participation (show_id);

create index if not exists idx_show_participation_company_id
  on public.show_participation (company_id);
