// List of available industries for Shows
export const INDUSTRIES = [
    'Medical Equipment',
    'Building & Construction',
    'Mobility',
    'IT & Technology',
    'Transport',
    'Private Label',
    'Packaging',
    'Education',
    'Property & Real Estate',
    'Entertainment',
    'Infrastructure',
    'Industrial & Manufacturing',
    'Beauty & Cosmetics',
    'Oil & Gas',
    'Art & Craft',
    'Healthcare',
    'Food & Beverage',
    'Science & Research',
    'Events & Exhibitions',
    'Agriculture',
    'Safety & Security',
    'Travel & Tourism',
    'Finance & Banking',
    'Automotive',
    'Plastic',
    'Horeca',
    'Animals & Pets',
    'Jewellery',
    'Interiors & Design',
    'Ceramic & Glass',
    'HVAC',
    'Food Manufacturing',
    'Defence & Security',
    'Bridal & Wedding',
    'Utility',
    'Fabric & Textiles',
    'Miscellaneous',
    'Marine & Energy',
    'Leisure & Sports',
    'Tech & IT',
    'Broadcasting',
    'Print',
    'Energy',
    'Aviation & Aerospace',
    'Paper',
    'Tobacco',
    'Book',
    'Gaming',
    'Homeware',
    'Design & Architecture',
    'Lights & Home Automation',
    'AVL',
    'Coating'
];

